/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:65e22a51-f8bd-4d1e-afee-09ea8fefea5f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_U9k4vD1P6",
    "aws_user_pools_web_client_id": "7tan4cf9jucg8q4nsrk74k91v6",
    "oauth": {}
};


export default awsmobile;
